Livraria.v1/Controllers/EmprestimoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Livraria.v1.Models;
using Livraria.v1.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Livraria.v1.Controllers
{
    public class EmprestimoController : Controller
    {
        private readonly IEmprestimoRepository emprestimoRepository;
        private readonly IUsuarioRepository usuarioRepository;
        private readonly ILivroRepository livroRepository;

        public EmprestimoController(IEmprestimoRepository emprestimoRepository
            , IUsuarioRepository usuarioRepository, ILivroRepository livroRepository)
        {
            this.emprestimoRepository = emprestimoRepository;
            this.usuarioRepository = usuarioRepository;
            this.livroRepository = livroRepository;
        }

        public IActionResult EmprestimoHome()
        {
            return View(emprestimoRepository.GetEmprestimo());
        }

        public IActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Inserir(Emprestimo emprestimo)
        {
            emprestimo.DataDevolucao = emprestimo.DataEmprestimo.AddDays(30);
            emprestimoRepository.Inserir(emprestimo);
            return RedirectToAction("EmprestimoHome");
        }

        public IActionResult Reserva()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Reserva(Reserva reserva)
        {
            emprestimoRepository.Reservar(reserva);
            return RedirectToAction("EmprestimoHome");
        }

        [HttpPost]
        public IActionResult Devolver([FromBody]int id)
        {
            emprestimoRepository.Devolver(id);
            return RedirectToAction(nameof(EmprestimoHome));
        }

        [HttpPost]
        public IActionResult Atraso([FromBody] int id)
        {
            emprestimoRepository.Atraso(id);
            return RedirectToAction(nameof(EmprestimoHome));
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Reservar(Emprestimo emprestimo)
        {
            emprestimo.DataDevolucao = emprestimo.DataEmprestimo.AddDays(30);
            emprestimoRepository.Inserir(emprestimo);
            return RedirectToAction("EmprestimoHome");
        }

        [HttpPost]
        public ConsultaUsuarioResponse ConsultaUsuario([FromBody] string valor)
        {
            return usuarioRepository.GetUsuarioPorNomeOuCpf(valor);
        }

        [HttpPost]
        public ConsultaLivroResponse ConsultaLivro([FromBody] string valor)
        {
            return livroRepository.GetLivroPorTituloOuAutor(valor);
        }
    }
}

Livraria.v1/Controllers/InstituicaoEnsinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Livraria.v1.Models;
using Livraria.v1.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Livraria.v1.Controllers
{
    public class InstituicaoEnsinoController : Controller
    {
        private readonly IInstituicaoEnsinoRepository instituicaoEnsinoRepository;

        public InstituicaoEnsinoController(IInstituicaoEnsinoRepository instituicaoEnsinoRepository)
        {
            this.instituicaoEnsinoRepository = instituicaoEnsinoRepository;
        }

        public IActionResult InstituicaoEnsinoHome()
        {
            return View(instituicaoEnsinoRepository.GetInstituicaoEnsino());
        }

        public IActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instituicaoEnsino = instituicaoEnsinoRepository.GetInstituicaoEnsino(id).FirstOrDefault();
            if (instituicaoEnsino == null)
            {
                return NotFound();
            }

            return View(instituicaoEnsino);
        }

        public IActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Inserir(InstituicaoEnsino instituicaoEnsino)
        {
            if (ModelState.IsValid)
            {
                instituicaoEnsino.Ativo = true;
                instituicaoEnsinoRepository.Inserir(instituicaoEnsino);
                return RedirectToAction("InstituicaoEnsinoHome");
            }

            return View(instituicaoEnsino);
        }

        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instituicaoEnsino = instituicaoEnsinoRepository.GetInstituicaoEnsino(id).FirstOrDefault();
            if (instituicaoEnsino == null)
            {
                return NotFound();
            }
            return View(instituicaoEnsino);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, InstituicaoEnsino instituicaoEnsino)
        {
            if (id != instituicaoEnsino.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    instituicaoEnsinoRepository.Atualizar(instituicaoEnsino);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!instituicaoEnsinoRepository.InstituicaoEnsinoExists(instituicaoEnsino.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("InstituicaoEnsinoHome");
            }
            return View(instituicaoEnsino);
        }

        public IActionResult AlterarStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instituicaoEnsino = instituicaoEnsinoRepository.GetInstituicaoEnsino(id).FirstOrDefault();
            if (instituicaoEnsino == null)
            {
                return NotFound();
            }

            return View(instituicaoEnsino);
        }

        // POST: Livroes/Delete/5
        [HttpPost]
        public IActionResult AlterarStatusConfirmado([FromBody] int id)
        {
            instituicaoEnsinoRepository.AlterarStatus(id);
            return RedirectToAction("InstituicaoEnsinoHome");
        }
    }
}

Livraria.v1/Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Livraria.v1.Models;
using Livraria.v1.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Livraria.v1.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroRepository livroRepository;

        public LivroController(ILivroRepository livroRepository)
        {
            this.livroRepository = livroRepository;
        }

        public IActionResult LivroHome()
        {
            return View(livroRepository.GetLivro());
        }

        public IActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = livroRepository.GetLivro(id).FirstOrDefault();
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        public IActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Inserir(Livro livro)
        {
            if (ModelState.IsValid)
            {
                livro.Ativo = true;
                livroRepository.Inserir(livro);
                return RedirectToAction("LivroHome");
            }
            return View(livro);
        }

        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = livroRepository.GetLivro(id).FirstOrDefault();
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    livroRepository.Atualizar(livro);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!livroRepository.LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("LivroHome");
            }
            return View(livro);
        }

        public IActionResult AlterarStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = livroRepository.GetLivro(id).FirstOrDefault();
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        // POST: Livroes/Delete/5
        [HttpPost]
        public IActionResult AlterarStatusConfirmado([FromBody]int id)
        {
            livroRepository.AlterarStatus(id);
            return RedirectToAction("LivroHome");
        }
    }
}

Livraria.v1/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Livraria.v1.Models;
using Livraria.v1.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Livraria.v1.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepository usuarioRepository;
        private readonly IInstituicaoEnsinoRepository instituicaoEnsinoRepository;

        public UsuarioController(IUsuarioRepository usuarioRepository,
            IInstituicaoEnsinoRepository instituicaoEnsinoRepository)
        {
            this.usuarioRepository = usuarioRepository;
            this.instituicaoEnsinoRepository = instituicaoEnsinoRepository;
        }

        public IActionResult UsuarioHome()
        {
            return View(usuarioRepository.GetUsuario());
        }

        public IActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = usuarioRepository.GetUsuario(id).FirstOrDefault();
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        public IActionResult Inserir()
        {
            IList<InstituicaoEnsino> itens = instituicaoEnsinoRepository.GetInstituicaoEnsino();
            if (itens.Count > 0)
            {
                ViewBag.Instituicoes = itens.Select(c => new SelectListItem() { Text = c.Nome, Value = c.Id.ToString() }).ToList();
                return View();
            }

            throw new ArgumentException("Erro ao carregar as Instituições de Ensino");
        }

        [HttpPost]
        public IActionResult Inserir(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Ativo = true;
                usuarioRepository.Inserir(usuario);
                return RedirectToAction(nameof(UsuarioHome));
            }
            return View(usuario);
        }

        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IList<InstituicaoEnsino> itens = instituicaoEnsinoRepository.GetInstituicaoEnsino();
            if (itens == null || itens.Count == 0)                
                return NotFound();

            var usuario = usuarioRepository.GetUsuario(id).FirstOrDefault();
            if (usuario == null)
            {
                return NotFound();
            }

            ViewBag.Instituicoes = itens.Select(c => new SelectListItem() 
            { 
                Text = c.Nome, 
                Value = c.Id.ToString(), 
                Selected = (c.Id == usuario.InstituicaoEnsino.Id) 
            }).ToList();

            return View(usuario);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    usuarioRepository.Atualizar(usuario);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!usuarioRepository.UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("UsuarioHome");
            }
            return View(usuario);
        }

        public IActionResult AlterarStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = usuarioRepository.GetUsuario(id).FirstOrDefault();
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Livroes/Delete/5
        [HttpPost]
        public IActionResult AlterarStatusConfirmado([FromBody] int id)
        {
            usuarioRepository.AlterarStatus(id);
            return RedirectToAction("UsuarioHome");
        }
    }
}

Livraria.v1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Empréstimos To Do</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/fontawesome/css/all.css" rel="stylesheet">
        <script defer src="~/lib/fontawesome/js/all.js"></script>
        <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css">
        @*<script src="https://kit.fontawesome.com/177c767a7d.js" crossorigin="anonymous"></script>*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/lib/fontawesome/css/all.css" rel="stylesheet">
        <script defer src="~/lib/fontawesome/js/all.js"></script>
        <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css">
        @*<script src="https://kit.fontawesome.com/177c767a7d.js" crossorigin="anonymous"></script>*@
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Emprestimo" asp-action="EmprestimoHome" class="navbar-brand">Empréstimos</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Usuario" asp-action="UsuarioHome">Usuário</a></li>
                    <li><a asp-area="" asp-controller="InstituicaoEnsino" asp-action="InstituicaoEnsinoHome">Instituição de Ensino</a></li>
                    <li><a asp-area="" asp-controller="Livro" asp-action="LivroHome">Livro</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Aaron Lesbão Dumont</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>